In [6]:
import numpy as np
print(np.__version__)

1.22.3


In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [21]:
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
arr = np.arange(10)
out = np.where(arr%2==1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [26]:
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
d = np.r_[a, b]
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([a, b], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [38]:
a = np.array([1,2,3])
np.r_[np.repeat(a,4), np.tile(a,3)]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [41]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [55]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [56]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [63]:
pair_max = np.vectorize(maxx, otypes=[float])

In [64]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [71]:
arr = np.arange(9).reshape(3,3)
arr
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [73]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[8.35498482, 7.05640278, 7.77714461],
       [5.89782665, 6.88863372, 6.85493024],
       [7.205072  , 7.0673114 , 7.63185844],
       [7.36094754, 8.21110582, 8.54505201],
       [5.73340351, 6.12247475, 5.00691679]])

In [74]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.089, 0.204, 0.164],
       [0.637, 0.255, 0.382],
       [0.854, 0.339, 0.695],
       [0.828, 0.887, 0.722]])

In [76]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr   
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [78]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [79]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [82]:
np.set_printoptions(threshold=sys.maxsize)
a

NameError: name 'sys' is not defined

In [83]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)